version: "3"
services:
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent
    depends_on:
      - "victoriametrics"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./scrape_config.yml:/etc/prometheus/scrape_config.yml
    command:
      - "--promscrape.config=/etc/prometheus/scrape_config.yml"
      - "--remoteWrite.url=http://victoriametrics:9999/api/v1/write"
    restart: always

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - 9999:9999
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:9999"
    restart: always

volumes:
  vmagentdata: {}
  vmdata: {}
